### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by ddavidebor** [r-spacex/Enceladus#9]
What does this piece of software do?

**Comment by jhpratt** [comment]
In conjunction with Titan (which is also in this organization), Enceladus will eventually overtake Mission Control as the preferred way to host launch threads. It will have a number of new features, like the ability to reorder sections without copy-pasting, as well as adding and removing sections.

I have no time frame for a release, though I will make a post on the SpaceX subreddit announcing it before it's widely used. I've already got a post drafted, but I still need to implement the host's features.

The current status of Enceladus is a bit slow, as I'm upstreaming a number of changes in Titan that will allow it to support significantly more concurrent users — I suspect it can handle a couple thousand now, but I need far more than that.

If you have any other questions, feel free to ask! I'm keeping some info quiet, but the general idea I don't mind.
